# Generated by Django 5.2.13 on 2026-05-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_reservation_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('DONE', 'Hoàn thành'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=15),
        ),
    ]
