# Generated by Django 5.2.13 on 2026-05-24 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_user_status_alter_category_id_alter_chatsession_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
