# Generated by Django 5.2.13 on 2026-05-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_category_id_alter_chatsession_id_alter_dish_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('CONFIRMED', 'Đã xác nhận'), ('CANCELLED', 'Đã hủy'), ('DONE', 'Đã hoàn thành')], default='PENDING', max_length=15),
        ),
    ]
